---
dist: xenial
sudo: required

language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - deactivate
  - |
    sudo apt-key adv --recv-keys \
      --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32 40976EAF437D05B5
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-ce

install:
  - sudo pip install ansible ansible-lint docker-py molecule
  - ansible --version
  - molecule --version

before_script:
  - docker ps -a

script:
  - molecule test

after_script:
  - docker ps -a
  - curl http://localhost
