---
- name: ensure that apt-transport-https presented
  package:
    name: apt-transport-https
    state: present
  become: yes

- name: add Elastic signing key
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present
  become: yes

- name: add Elastic repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ elastic_version }}/apt stable main"
    state: present
    filename: "elastic-{{ elastic_version }}"
  become: yes
