---
# tasks file for ansible-elastic-metricbeat
- import_tasks: "{{ ansible_os_family }}.yml"
  tags:
    - install-packages

- name: Install Metricbeat
  package:
    name: metricbeat
    state: present
  notify: restart_metricbeat
  tags:
    - install-packages
  become: True

- name: Copy Metricbeat configuration.
  template:
    src: metricbeat.yml.j2
    dest: "/etc/metricbeat/metricbeat.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart_metricbeat
  become: True
