---
# tasks file for ansible-elastic-metricbeat
include_tasks: "{{ ansible_os_family  }}.yml"

- name: Install Metricbeat
  package:
    name: metricbeat
    state: present
  notify: restart_metricbeat
  become: yes

- name: Copy Metricbeat configuration.
  template:
    src: metricbeat.yml.j2
    dest: "/etc/metricbeat/metricbeat.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart_metricbeat
  become: yes
